---
Parameters: 
  DBPassword: 
    NoEcho: true
    Description: 'The database admin account password'
    Type: String
    MinLength: 8
    MaxLength: 41
    AllowedPattern: ^[a-zA-Z0-9]*$

Resources:
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties: 
      CidrBlock: 10.1.3.0/24
      VpcId: 'vpc-0d8b58f3d5536f853' # replace with Ref
      AvailabilityZone: 'eu-central-1c'
      Tags:
      - Key: Name
        Value: lucid_private_subnet_2

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: 'subnet group for the test RDS instance'
      DBSubnetGroupName: lucid_db_subnet_group
      SubnetIds: 
        - !Ref PrivateSubnet2
        - subnet-09510f16a5e18ca66 # lucid_private_subnet
      Tags: 
      - Key: Name
        Value: lucid_db_subnet_group

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties: 
      AllocatedStorage: '10'
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: lucid-db
      DBSubnetGroupName: !Ref DBSubnetGroup
      Engine: MySQL
      EngineVersion: '5.7.26'
      MasterUsername: 'admin'
      MasterUserPassword: !Ref DBPassword
      MultiAZ: false
      PubliclyAccessible: false
      VPCSecurityGroups: 
        - sg-01be398caf79b060a #!Ref DBSecurityGroup

