---
Parameters: 
  PublicSubnetCidrBlock: 
    Type: String
    Description: Provide a valid CIDR block for the public subnet

  PrivateSubnetCidrBlock: 
    Type: String
    Description: Provide a valid CIDR block for the private subnet

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.1.0.0/16
      Tags:
      - Key: Name
        Value: lucid_vpc

  Igw:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: lucid_igw 

  IgwVpcAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId: !Ref Igw
      VpcId: !Ref Vpc

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties: 
      CidrBlock: !Ref PublicSubnetCidrBlock
      VpcId: !Ref Vpc
      Tags:
      - Key: Name
        Value: lucid_public_subnet

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties: 
      CidrBlock: !Ref PrivateSubnetCidrBlock
      VpcId: !Ref Vpc
      Tags:
      - Key: Name
        Value: lucid_private_subnet

  PublicSubnetRT:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref Vpc
      Tags:
      - Key: Name
        Value: lucid_public_subnet_rt

  PublicSubnetRTAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref PublicSubnetRT
      SubnetId: !Ref PublicSubnet

  PublicTrafficRoute:
    Type: AWS::EC2::Route
    Properties: 
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref Igw
      RouteTableId: !Ref PublicSubnetRT
